name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Replace token in config
        run: |
          sed -i "s/{{HUGGING_FACE_TOKEN}}/$HUGGING_FACE_TOKEN/g" src/config.js
        env:
          HUGGING_FACE_TOKEN: ${{ secrets.HUGGING_FACE_TOKEN }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}  # Utilisez votre PAT ici
          publish_dir: ./  # Dossier à publier (racine du projet)