name: Deploy  # Nom du workflow

on: 
  push:
    branches:
      - main  # Exécuter l'action quand on pousse du code sur "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Passer le secret à l'environnement
        run: echo "HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}" >> $GITHUB_ENV

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Choisis la version de Node.js

      - name: Installer les dépendances
        run: npm install  # Installe les dépendances si nécessaire

      - name: Exécuter le script JavaScript
        run: node js/main.js  # Exécute ton fichier JS
